#!/bin/bash -x

if [ `command -v curl` ]; then
  curl -sL https://releases.rancher.com/install-docker/${docker_version_server}.sh | sh
elif [ `command -v wget` ]; then
  wget -qO- https://releases.rancher.com/install-docker/${docker_version_server}.sh | sh
fi

sudo usermod -aG docker ${user}

sleep 10

${join_command} --worker --controlplane --etcd